### ISSUE TITLE
ftplib.error_perm

### ISSUE THREAD

**Issue by zxdawn** [zxdawn/Himawari-8-gridded#3]
```
Traceback (most recent call last):
  File "count2tbb.py", line 403, in <module>
    main()
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "count2tbb.py", line 319, in main
    ftp.login(user, password)
  File "/home/xin/Software/anaconda3/lib/python3.6/ftplib.py", line 420, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/home/xin/Software/anaconda3/lib/python3.6/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/home/xin/Software/anaconda3/lib/python3.6/ftplib.py", line 246, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Sorry, max 40 users --try again later

```

**Comment by zxdawn** [comment]
Just happen once, close now.
